"""Public Agent API for the safe M2-V0 baseline."""

from .doctor import (
    FIXED_V0_LESSONS,
    AgentDecision,
    DoctorAgent,
    DoctorAgentConfig,
    DoctorAgentInput,
    DoctorAgentInterface,
    FixedV0Curriculum,
)
from .fake_llm import ScriptedFakeLLM
from .deepseek import (
    DeepSeekAdapterConfig,
    DeepSeekAdapterError,
    DeepSeekAuthenticationError,
    DeepSeekBudgetExceededError,
    DeepSeekChatAdapter,
    DeepSeekConfigurationError,
    DeepSeekEmptyContentError,
    DeepSeekInvalidJSONError,
    DeepSeekMissingAPIKeyError,
    DeepSeekModelDiscovery,
    DeepSeekModelUnavailableError,
    DeepSeekProviderError,
    DeepSeekRateLimitError,
    DeepSeekRequestBudgetGuard,
    DeepSeekRequestReservation,
    DeepSeekResponseFieldError,
    DeepSeekTimeoutError,
    DeepSeekTransportError,
    DeepSeekTruncatedOutputError,
    DeepSeekUsageUnavailableError,
)
from .llm import (
    ChatMessage,
    ChatRole,
    LLMAdapter,
    LLMAdapterError,
    LLMRequest,
    LLMResponse,
)
from .v1_doctor import (
    V1_SYSTEM_PROMPT,
    V1DoctorAgent,
    V1DoctorAgentConfig,
    V1DoctorAgentInput,
    V1DoctorAgentInterface,
    V1PromptContext,
)

__all__ = [
    "FIXED_V0_LESSONS",
    "AgentDecision",
    "ChatMessage",
    "ChatRole",
    "DoctorAgent",
    "DoctorAgentConfig",
    "DoctorAgentInput",
    "DoctorAgentInterface",
    "FixedV0Curriculum",
    "DeepSeekAdapterConfig",
    "DeepSeekAdapterError",
    "DeepSeekAuthenticationError",
    "DeepSeekBudgetExceededError",
    "DeepSeekChatAdapter",
    "DeepSeekConfigurationError",
    "DeepSeekEmptyContentError",
    "DeepSeekInvalidJSONError",
    "DeepSeekMissingAPIKeyError",
    "DeepSeekModelDiscovery",
    "DeepSeekModelUnavailableError",
    "DeepSeekProviderError",
    "DeepSeekRateLimitError",
    "DeepSeekRequestBudgetGuard",
    "DeepSeekRequestReservation",
    "DeepSeekResponseFieldError",
    "DeepSeekTimeoutError",
    "DeepSeekTransportError",
    "DeepSeekTruncatedOutputError",
    "DeepSeekUsageUnavailableError",
    "LLMAdapter",
    "LLMAdapterError",
    "LLMRequest",
    "LLMResponse",
    "ScriptedFakeLLM",
    "V1_SYSTEM_PROMPT",
    "V1DoctorAgent",
    "V1DoctorAgentConfig",
    "V1DoctorAgentInput",
    "V1DoctorAgentInterface",
    "V1PromptContext",
]
